web:
    image: httpd
    ports:
        - 80:80
    volumes:
        - ./htdocs:/usr/local/apache2/htdocs

node:
    image: node
    ports:
        - 8080:8080
    volumes:
        - ./node:/mnt
    tty: true
